name: Bug Report
description: Report incorrect information or broken processes
title: "fix: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Clear description of what's wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should be happening instead?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Any other context about the problem
