name: Documentation Update
description: Template for documentation changes or additions
title: "docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - Process Guide
        - Template
        - Example
        - Checklist
        - Best Practices
    validations:
      required: true

  - type: textarea
    id: what-needs-updating
    attributes:
      label: What needs to be updated?
      placeholder: Clear description of what documentation needs to be added or changed
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      placeholder: Outline the specific changes or additions you're proposing

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Any other context or screenshots about the documentation update
